//! Logical OUTER return-channel capabilities.
//!
//! The value is carried in the existing envelope field so older relay code
//! can continue copying it without learning a new body message. The suffix is
//! a bearer capability generated by the OUTER; an agent must not bind a socket
//! for a channel that does not carry one.

const SEPARATOR: char = '~';
const MIN_CAPABILITY_BYTES: usize = 32;

pub fn with_capability(logical: &str, capability: &str) -> String {
    format!("{logical}{SEPARATOR}{capability}")
}

pub fn is_capability_channel(channel: &str) -> bool {
    let Some((logical, capability)) = channel.rsplit_once(SEPARATOR) else {
        return false;
    };
    !logical.is_empty()
        && capability.len() >= MIN_CAPABILITY_BYTES * 2
        && capability.len().is_multiple_of(2)
        && capability.bytes().all(|byte| byte.is_ascii_hexdigit())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_channel_requires_a_long_hex_bearer_capability() {
        let channel = with_capability("outer", &"ab".repeat(MIN_CAPABILITY_BYTES));
        assert!(is_capability_channel(&channel));
        assert!(!is_capability_channel("outer"));
        assert!(!is_capability_channel("outer~abcd"));
        assert!(!is_capability_channel(&format!(
            "outer~{}",
            "zz".repeat(MIN_CAPABILITY_BYTES)
        )));
    }
}
