[package]
name = "p4-agent-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
p4-adapter = { path = "../adapters/adapter" }
p4-protocol = { path = "../protocol" }
tokio = { version = "1.48.0", features = ["net", "rt-multi-thread", "sync", "time", "io-util", "macros", "fs"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Storage_FileSystem"] }

[dev-dependencies]
p4-mock = { path = "../adapters/mock" }
p4-link = { path = "../../tools/link" }
