// Independent literal vectors: this script imports no Rust code, wire codec,
// production projection helper, or generated trace. Values below are the
// declared test workloads. Node's standard SHA-256 is the digest oracle.
// Run this file and compare stdout byte-for-byte (after JSON parsing) with
// vectors-v1.json; that checked-in file is not generated by the Rust tests.
import { createHash } from 'node:crypto';

const u32 = value => {
  const bytes = Buffer.alloc(4);
  bytes.writeUInt32LE(value);
  return bytes;
};
const u64 = value => {
  const bytes = Buffer.alloc(8);
  bytes.writeBigUInt64LE(BigInt(value));
  return bytes;
};
const text = value => {
  const bytes = Buffer.from(value, 'utf8');
  return Buffer.concat([u32(bytes.length), bytes]);
};
const sha = bytes => createHash('sha256').update(bytes).digest();
const authority = (headAddress, headNode, headGeneration, outerAddress, channel,
  connection, load, session, request, submission, slot, incarnation) => Buffer.concat([
  Buffer.from('P4_ISSUE_AUTHORITY_V1\0', 'utf8'),
  text(headAddress), text(headNode), u64(headGeneration),
  text(outerAddress), text(channel), u64(connection), u64(load),
  text(session), text(request), text(submission), u32(slot), u64(incarnation),
]);

// Literal entries are ALREADY in their declared canonical order. Do not sort
// or call an implementation under test here. phase: 0=Prefill,1=Decode,
// 2=Verify,3=Replay; each entry retains every position rather than min/max.
const issue = (previous, count, ordinal, entries) => Buffer.concat([
  Buffer.from('P4_ISSUED_WORK_V1\0', 'utf8'), previous, u64(count), u64(ordinal),
  u32(entries.length),
  ...entries.flatMap(([execution, rows]) => [
    u64(execution), u32(rows.length),
    ...rows.flatMap(([phase, position]) => [Buffer.from([phase]), u32(position)]),
  ]),
]);
const vector = (seedBytes, steps) => {
  const seed = sha(seedBytes);
  let previous = seed;
  return {
    authority_hex: seedBytes.toString('hex'),
    authority_digest: seed.toString('hex'),
    initial_digest: seed.toString('hex'),
    steps: steps.map(([ordinal, entries], index) => {
      const bytes = issue(previous, index + 1, ordinal, entries);
      previous = sha(bytes);
      return {
        issue_count: index + 1,
        logical_ordinal: ordinal,
        canonical_hex: bytes.toString('hex'),
        digest: previous.toString('hex'),
      };
    }),
  };
};
const vectors = {
  format: 1,
  unit: vector(authority(
    'tcp://127.0.0.1:42001', 'head', 3,
    'tcp://127.0.0.2:42002', 'outer-channel', 5,
    7, 'session-\u03b1', 'request-a', 'outer-event-11', 2, 13,
  ), [
    [1, [[11, [[0, 0], [0, 2]]], [12, [[0, 1]]]]],
    [9, [[22, [[2, 3], [2, 4]]]]],
    [12, [[23, [[3, 3], [3, 4]]]]],
  ]),
  accept: vector(authority(
    'tcp://127.0.0.1:42001', 'n0', 1,
    'tcp://127.0.0.1:42000', 'proof', 7,
    1, 'witness-session', 'a', 'submit-a', 0, 17,
  ), [
    [1, [[11, [[0, 0], [0, 1]]], [12, [[0, 2]]], [13, [[0, 3]]]]],
    [4, [[21, [[0, 4], [0, 5]]], [22, [[0, 6], [0, 7]]]]],
  ]),
  ordinary: vector(authority(
    'tcp://127.0.0.1:42999', 'loop-0', 1,
    'tcp://127.0.0.1:42999', 'loop-output', 1,
    1, 'loop-session', 'one',
    'outer:tcp://127.0.0.1:42999:loop-output:1:1', 0, 1,
  ), [
    [1, [[1, [[0, 0], [0, 1]]], [2, [[0, 2], [0, 3]]]]],
    [2, [[3, [[0, 4], [0, 5]]], [4, [[0, 6]]]]],
    [3, [[5, [[1, 7]]]]],
    [4, [[6, [[1, 8]]]]],
    [5, [[7, [[1, 9]]]]],
    [6, [[8, [[1, 10]]]]],
  ]),
  mixed_a: vector(authority(
    'tcp://127.0.0.1:42999', 'loop-0', 1,
    'tcp://127.0.0.1:42991', 'issue-owner-a', 11,
    1, 'loop-session', 'issue-owner-a',
    'outer:tcp://127.0.0.1:42991:issue-owner-a:11:1', 0, 1,
  ), [[1, [[1, [[0, 0]]]]]]),
  mixed_b: vector(authority(
    'tcp://127.0.0.1:42999', 'loop-0', 1,
    'tcp://127.0.0.1:42992', 'issue-owner-b', 12,
    1, 'loop-session', 'issue-owner-b',
    'outer:tcp://127.0.0.1:42992:issue-owner-b:12:1', 1, 2,
  ), [[1, [[1, [[0, 0]]]]]]),
};
process.stdout.write(`${JSON.stringify(vectors, null, 2)}\n`);
